[colors.bright]
black = "#6a6a6a"
blue = "#ffaf00"
cyan = "#00afaf"
green = "#afd700"
magenta = "#ffaf00"
red = "#e74c3c"
white = "#5f8787"
yellow = "#f1c40f"

[colors.cursor]
cursor = "#808080"
text = "#424242"

[colors.normal]
black = "#333333"
blue = "#5fafd7"
cyan = "#2ecc71"
green = "#5faf00"
magenta = "#808080"
red = "#af005f"
white = "#f2f2f2"
yellow = "#f1c40f"

[colors.primary]
background = "#000000"
foreground = "#f1f1f1"

# [colors.primary]
# background= "#ffffff"
# foreground= "#1F2328"
#
# [colors.normal]
# black= "#24292f"
# red= "#cf222e"
# green= "#116329"
# yellow= "#4d2d00"
# blue= "#0969da"
# magenta= "#8250df"
# cyan= "#1b7c83"
# white= "#6e7781"
#
# [colors.bright]
# black= "#57606a"
# red= "#a40e26"
# green= "#1a7f37"
# yellow= "#633c01"
# blue= "#218bff"
# magenta= "#8250df"
# cyan= "#1b7c83"
# white= "#6e7781"

[font]
size = 12.5

[font.normal]
# family = "Gitlab Mono"
family = "Fira Code"
style = "Regular"

[shell]
# args = ["new"]
# program = "/usr/bin/tmux"
program = "/usr/local/bin/zellij"
