# Configuration for Alacritty, the GPU enhanced terminal emulator.
shell:
  program: /usr/bin/tmux
  args:
    - new-session

font:
  size: 14
  normal:
    # family: DejaVuSansMono
    family: UbuntuMono
    style: Nerd

colors:
  primary:
    background: "0x080808"
    foreground: "0xc1c1c1"

  cursor:
    text: "0x424242"
    cursor: "0x808080"

  normal:
    black: "0x080808"
    red: "0xaf005f"
    green: "0x5faf00"
    yellow: "0xf1c40f"
    blue: "0x5fafd7"
    magenta: "0x808080"
    cyan: "0x2ecc71"
    white: "0xf2f2f2"

  bright:
    black: "0x6a6a6a"
    red: "0xe74c3c"
    green: "0xafd700"
    yellow: "0xf1c40f"
    blue: "0xffaf00"
    magenta: "0xffaf00"
    cyan: "0x00afaf"
    white: "0x5f8787"
