shell:
  program: /usr/bin/tmux
  args:
    - new


font:
  size: 11.5
  normal:
    # family: FiraMono
    # style: Normal
    # family: DejaVuSansMono
    # family: UbuntuMono
    # style: Nerd
    family: GitLabMono
    style: Regular

colors:
  primary:
    background: "#000000"
    foreground: "#c1c1c1"

  cursor:
    text: "#424242"
    cursor: "#808080"

  normal:
    black: "#000000"
    red: "#af005f"
    green: "#5faf00"
    yellow: "#f1c40f"
    blue: "#5fafd7"
    magenta: "#808080"
    cyan: "#2ecc71"
    white: "#f2f2f2"

  bright:
    black: "#6a6a6a"
    red: "#e74c3c"
    green: "#afd700"
    yellow: "#f1c40f"
    blue: "#ffaf00"
    magenta: "#ffaf00"
    cyan: "#00afaf"
    white: "#5f8787"
